########################################
## submit description file
########################################

Universe   = vanilla
Executable = /home/enpaudel/icecube/triggerStudy/triggerScripts/runDetectorClusterChunk.sh
Log        = /scratch/enpaudel/log/trigStudyDAT002270.log
Output     = /data/user/enpaudel/triggerStudy/log/trigStudyDAT002270.out
Error      = /data/user/enpaudel/triggerStudy/log/trigStudyDAT002270.err
request_cpus = 1
request_memory = 4GB
request_disk = 1GB
#request_gpus = 1
#should_transfer_files   = IF_NEEDED
#when_to_transfer_output = ON_EXIT
#notification = Complete
#notify_user = <email-address>
#priority = <integer>
##long job
priority = 5
#set arguments to executable
arguments = /data/sim/IceTop/2009/generated/CORSIKA-ice-top/12605/6.9/DAT002270.bz2 
queue 1
